"""changes post submission based on review comments

Revision ID: 1499c84f6f50
Revises: f62a8e225cb5
Create Date: 2024-06-23 22:18:42.912392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1499c84f6f50'
down_revision = 'f62a8e225cb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Artist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seeking_venue', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('seeking_description', sa.String(length=500), nullable=True))
        batch_op.drop_column('descForVenue')
        batch_op.drop_column('lookingForVenue')
        batch_op.drop_column('genres')

    with op.batch_alter_table('Shows', schema=None) as batch_op:
        batch_op.drop_column('artist_name')
        batch_op.drop_column('venue_name')

    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seeking_talent', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('seeking_description', sa.String(length=500), nullable=True))
        batch_op.drop_column('lookingForTalent')
        batch_op.drop_column('descForTalent')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descForTalent', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('lookingForTalent', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_column('seeking_description')
        batch_op.drop_column('seeking_talent')

    with op.batch_alter_table('Shows', schema=None) as batch_op:
        batch_op.add_column(sa.Column('venue_name', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('artist_name', sa.VARCHAR(), autoincrement=False, nullable=True))

    with op.batch_alter_table('Artist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('genres', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('lookingForVenue', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('descForVenue', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
        batch_op.drop_column('seeking_description')
        batch_op.drop_column('seeking_venue')

    # ### end Alembic commands ###
