"""Addition of missing model columns

Revision ID: 28da9db54e7c
Revises: 
Create Date: 2024-06-17 20:47:12.501305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28da9db54e7c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('todoapp')
    op.drop_table('customers')
    op.drop_table('todo_table')
    op.drop_table('persons')
    with op.batch_alter_table('Artist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lookingForVenue', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('descForVenue', sa.String(length=500), nullable=True))

    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lookingForTalent', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('descForTalent', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.drop_column('descForTalent')
        batch_op.drop_column('lookingForTalent')

    with op.batch_alter_table('Artist', schema=None) as batch_op:
        batch_op.drop_column('descForVenue')
        batch_op.drop_column('lookingForVenue')

    op.create_table('persons',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='persons_pkey')
    )
    op.create_table('todo_table',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='todo_table_pkey')
    )
    op.create_table('customers',
    sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('first_name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('phone_number', sa.VARCHAR(length=20), autoincrement=False, nullable=True)
    )
    op.create_table('todoapp',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('completed', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='todoapp_pkey')
    )
    # ### end Alembic commands ###
