"""empty message

Revision ID: f8e0473befc0
Revises: fb57b87fe7a8
Create Date: 2024-06-24 20:56:08.442606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8e0473befc0'
down_revision = 'fb57b87fe7a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Artist', schema=None) as batch_op:
        batch_op.drop_column('address1')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Artist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address1', sa.VARCHAR(length=120), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
